// apps/web/src/ui/form/ApplicationForm.vue
<script setup lang="ts">
import type { ApplicationStatus } from "@applytrack/core";
import {
  APPLICATION_SOURCES,
  CURRENCIES,
  INITIAL_STATUSES,
  LIMITS,
  WORK_MODES,
} from "@applytrack/core";
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";

import { bumpDataVersion } from "../../composables/useDataVersion";
import { useLeaveGuard } from "../../composables/useLeaveGuard";
import { showToast } from "../../composables/useToast";
import type { FormValues } from "../../form/form-values";
import { showsAppliedAt } from "../../form/form-values";
import { useApplicationForm } from "../../form/useApplicationForm";
import StatusBadge from "../components/StatusBadge.vue";
import FieldErrors from "./FieldErrors.vue";
import SelectField from "./SelectField.vue";
import TagInput from "./TagInput.vue";
import TextField from "./TextField.vue";

export type SaveOutcome = "saved" | "invalid" | "error";

const props = defineProps<{
  initial: FormValues;
  currentStatus?: ApplicationStatus;
  save: (values: FormValues) => Promise<SaveOutcome>;
}>();

const { t, locale } = useI18n();
const router = useRouter();

const form = useApplicationForm({
  initial: props.initial,
  ...(props.currentStatus && { currentStatus: props.currentStatus }),
});
const { values, issuesFor, isDirty, touch, submitted } = form;

const saving = ref(false);
const saveError = ref(false);
const announcement = ref("");

useLeaveGuard(isDirty, () => t("form.unsavedConfirm"));

const options = <T extends string>(list: readonly T[], prefix: string) =>
  computed(() => list.map((value) => ({ value, label: t(`${prefix}.${value}`) })));

const sourceOptions = options(APPLICATION_SOURCES, "source");
const workModeOptions = options(WORK_MODES, "workMode");
const currencyOptions = CURRENCIES.map((value) => ({ value, label: value }));

const showAppliedAt = computed(() => showsAppliedAt(props.currentStatus ?? values.status));

const salaryPreview = computed(() => {
  const amounts = [values.salaryMin, values.salaryMax]
    .filter((value) => value.trim() !== "")
    .map(Number);
  if (!amounts.length || amounts.some((amount) => !Number.isInteger(amount) || amount <= 0)) {
    return "";
  }
  const format = new Intl.NumberFormat(locale.value, {
    style: "currency",
    currency: values.currency,
    maximumFractionDigits: 0,
  });
  return amounts.map((amount) => format.format(amount)).join(" – ");
});

const salaryIssues = (field: string) =>
  issuesFor("salary").filter((issue) => issue.field === field);

const notesCount = computed(() =>
  t("form.hints.notesCount", {
    count: new Intl.NumberFormat(locale.value).format(Array.from(values.notes).length),
    max: new Intl.NumberFormat(locale.value).format(LIMITS.notes),
  }),
);

const leave = async () => {
  const back = router.options.history.state.back;
  if (typeof back === "string") router.back();
  else await router.push({ name: "board" });
};

const onSubmit = async () => {
  submitted.value = true;
  saveError.value = false;
  if (form.issues.value.length) {
    announcement.value = t("errors.VALIDATION_FAILED");
    await form.focusFirstError();
    return;
  }

  saving.value = true;
  try {
    const outcome = await props.save(values);
    if (outcome === "saved") {
      form.markSaved();
      bumpDataVersion();
      showToast(t("form.saved"));
      await leave();
    } else if (outcome === "invalid") {
      await form.focusFirstError();
    } else {
      saveError.value = true;
    }
  } catch {
    saveError.value = true;
  } finally {
    saving.value = false;
  }
};
</script>

<template>
  <form novalidate class="flex flex-col gap-6 pb-20 md:pb-0" @submit.prevent="onSubmit">
    <p class="text-ink-muted text-sm">{{ t("form.requiredHint") }}</p>
    <p class="sr-only" aria-live="assertive">{{ announcement }}</p>

    <fieldset class="border-border bg-surface grid gap-4 rounded-lg border p-4 md:grid-cols-2">
      <legend class="px-1 font-semibold">{{ t("form.groups.offer") }}</legend>
      <TextField
        v-model="values.company"
        name="company"
        :label="t('form.fields.company')"
        :issues="issuesFor('company')"
        :maxlength="LIMITS.company"
        required
        @blur="touch('company')"
      />
      <TextField
        v-model="values.position"
        name="position"
        :label="t('form.fields.position')"
        :issues="issuesFor('position')"
        :maxlength="LIMITS.position"
        required
        @blur="touch('position')"
      />
      <SelectField
        v-model="values.source"
        name="source"
        :label="t('form.fields.source')"
        :options="sourceOptions"
        :issues="issuesFor('source')"
        required
        placeholder
        @blur="touch('source')"
      />
      <SelectField
        v-model="values.workMode"
        name="workMode"
        :label="t('form.fields.workMode')"
        :options="workModeOptions"
        :issues="issuesFor('workMode')"
        required
        placeholder
        @blur="touch('workMode')"
      />
      <TextField
        v-model="values.jobUrl"
        name="jobUrl"
        type="url"
        :label="t('form.fields.jobUrl')"
        :placeholder="t('form.placeholders.jobUrl')"
        :issues="issuesFor('jobUrl')"
        :maxlength="LIMITS.jobUrl"
        @blur="touch('jobUrl')"
      />
      <TextField
        v-model="values.location"
        name="location"
        :label="t('form.fields.location')"
        :placeholder="t('form.placeholders.location')"
        :issues="issuesFor('location')"
        :maxlength="LIMITS.location"
        @blur="touch('location')"
      />
    </fieldset>

    <fieldset class="border-border bg-surface grid gap-4 rounded-lg border p-4 md:grid-cols-2">
      <legend class="px-1 font-semibold">{{ t("form.groups.process") }}</legend>

      <div v-if="currentStatus" class="flex flex-col gap-1">
        <p class="text-sm font-medium">{{ t("form.currentStatus") }}</p>
        <p><StatusBadge :status="currentStatus" /></p>
        <p class="text-ink-muted text-sm">{{ t("form.statusHint") }}</p>
      </div>
      <fieldset v-else class="flex flex-col gap-2">
        <legend class="mb-1 text-sm font-medium">
          {{ t("form.fields.status") }}<span aria-hidden="true" class="text-danger"> *</span>
        </legend>
        <div class="flex flex-wrap gap-2">
          <label
            v-for="status in INITIAL_STATUSES"
            :key="status"
            class="border-border has-checked:border-accent has-checked:bg-accent-soft flex min-h-11 cursor-pointer items-center gap-2 rounded-md border px-3"
          >
            <input
              :id="`field-status-${status}`"
              type="radio"
              name="status"
              class="accent-accent size-4"
              :value="status"
              :checked="values.status === status"
              @change="form.setStatus(status)"
            />
            {{ t(`status.${status}`) }}
          </label>
        </div>
        <FieldErrors id="error-status" :issues="issuesFor('status')" />
      </fieldset>

      <TextField
        v-if="showAppliedAt"
        v-model="values.appliedAt"
        name="appliedAt"
        type="date"
        :max="form.today()"
        :label="t('form.fields.appliedAt')"
        :issues="issuesFor('appliedAt')"
        @blur="touch('appliedAt')"
      />
    </fieldset>

    <fieldset
      class="border-border bg-surface grid gap-4 rounded-lg border p-4 md:grid-cols-3"
      aria-describedby="hint-salary error-salary"
    >
      <legend class="px-1 font-semibold">{{ t("form.groups.salary") }}</legend>
      <TextField
        v-model="values.salaryMin"
        name="salaryMin"
        type="number"
        :label="t('form.fields.salaryMin')"
        :issues="salaryIssues('salary.min')"
        @blur="touch('salary')"
      />
      <TextField
        v-model="values.salaryMax"
        name="salaryMax"
        type="number"
        :label="t('form.fields.salaryMax')"
        :issues="salaryIssues('salary.max')"
        @blur="touch('salary')"
      />
      <SelectField
        v-model="values.currency"
        name="currency"
        :label="t('form.fields.currency')"
        :options="currencyOptions"
        :issues="salaryIssues('salary.currency')"
        @blur="touch('salary')"
      />
      <div class="md:col-span-3">
        <p id="hint-salary" class="text-ink-muted text-sm">
          {{ t("form.hints.salary") }}
          <span v-if="salaryPreview" class="text-ink font-medium">{{ salaryPreview }}</span>
        </p>
        <FieldErrors id="error-salary" :issues="salaryIssues('salary')" />
      </div>
    </fieldset>

    <fieldset class="border-border bg-surface rounded-lg border p-4">
      <legend class="px-1 font-semibold">{{ t("form.groups.tags") }}</legend>
      <TagInput v-model="values.tags" :issues="issuesFor('tags')" @blur="touch('tags')" />
    </fieldset>

    <fieldset class="border-border bg-surface flex flex-col gap-1 rounded-lg border p-4">
      <legend class="px-1 font-semibold">{{ t("form.groups.notes") }}</legend>
      <label for="field-notes" class="sr-only">{{ t("form.fields.notes") }}</label>
      <textarea
        id="field-notes"
        v-model="values.notes"
        rows="5"
        :aria-invalid="issuesFor('notes').length > 0 || undefined"
        aria-describedby="hint-notes error-notes"
        class="border-border bg-surface aria-invalid:border-danger rounded-md border p-3"
        @blur="touch('notes')"
      />
      <p id="hint-notes" class="text-ink-muted text-right text-sm">{{ notesCount }}</p>
      <FieldErrors id="error-notes" :issues="issuesFor('notes')" />
    </fieldset>

    <p v-if="saveError" role="alert" class="text-danger text-sm font-medium">
      {{ t("form.saveError") }}
    </p>

    <div
      class="border-border bg-surface fixed inset-x-0 bottom-[calc(3.5rem+env(safe-area-inset-bottom))] z-10 flex gap-3 border-t p-3 md:static md:justify-end md:border-0 md:bg-transparent md:p-0"
    >
      <button
        type="button"
        class="border-border hover:bg-surface-muted min-h-11 flex-1 rounded-md border px-4 font-medium md:flex-none"
        @click="leave"
      >
        {{ t("form.cancel") }}
      </button>
      <button
        type="submit"
        class="bg-accent text-accent-ink min-h-11 flex-1 rounded-md px-6 font-semibold disabled:opacity-70 md:flex-none"
        :disabled="saving"
        :aria-busy="saving"
      >
        {{ saving ? t("form.saving") : t("form.save") }}
      </button>
    </div>
  </form>
</template>

// apps/mobile/src/screens/ApplicationForm.tsx
import type { ApplicationStatus } from "@applytrack/core";
import {
  APPLICATION_SOURCES,
  CURRENCIES,
  INITIAL_STATUSES,
  LIMITS,
  WORK_MODES,
} from "@applytrack/core";
import type { FieldGroup } from "@applytrack/presentation";
import { createFormatter, groupOf, showsAppliedAt } from "@applytrack/presentation";
import type { ReactNode, RefObject } from "react";
import { forwardRef, useImperativeHandle, useMemo, useRef } from "react";
import { useTranslation } from "react-i18next";
import type { ScrollView as ScrollViewType, TextInput, View as ViewType } from "react-native";
import {
  AccessibilityInfo,
  findNodeHandle,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Text,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { Button } from "../ui/Button";
import { Chip } from "../ui/Chip";
import { DateField } from "../ui/DateField";
import { TagField } from "../ui/TagField";
import { TextField } from "../ui/TextField";
import type { ApplicationFormState } from "./useApplicationForm";

type Section = "offer" | "process" | "salary" | "tags" | "notes";

const SECTION_OF: Readonly<Record<FieldGroup, Section>> = {
  company: "offer",
  position: "offer",
  jobUrl: "offer",
  source: "offer",
  workMode: "offer",
  location: "offer",
  status: "process",
  appliedAt: "process",
  salary: "salary",
  tags: "tags",
  notes: "notes",
};

const Group = ({
  title,
  children,
  onLayout,
}: {
  readonly title: string;
  readonly children: ReactNode;
  readonly onLayout: (y: number) => void;
}) => (
  <View
    onLayout={(event) => {
      onLayout(event.nativeEvent.layout.y);
    }}
    className="gap-4 rounded-lg border border-border bg-surface p-4"
  >
    <Text accessibilityRole="header" className="text-base font-semibold text-ink">
      {title}
    </Text>
    {children}
  </View>
);

const ChoiceGroup = ({
  label,
  required,
  options,
  selected,
  onSelect,
  issues,
  groupRef,
}: {
  readonly label: string;
  readonly required?: boolean;
  readonly options: readonly { value: string; label: string }[];
  readonly selected: string;
  readonly onSelect: (value: string) => void;
  readonly issues: readonly {
    field: string;
    code: string;
    meta?: Readonly<Record<string, string | number>>;
  }[];
  readonly groupRef?: RefObject<ViewType | null>;
}) => {
  const { t } = useTranslation();
  return (
    <View className="gap-2">
      <Text className="text-sm font-medium text-ink">
        {label}
        {required ? <Text className="text-danger"> *</Text> : null}
      </Text>
      <View
        ref={groupRef}
        accessible={false}
        accessibilityRole="radiogroup"
        accessibilityLabel={label}
        className="flex-row flex-wrap gap-2"
      >
        {options.map((option) => (
          <Chip
            key={option.value}
            role="radio"
            label={option.label}
            selected={selected === option.value}
            onPress={() => {
              onSelect(option.value);
            }}
          />
        ))}
      </View>
      {issues.map((issue) => (
        <Text key={`${issue.field}-${issue.code}`} className="text-sm text-danger">
          {t(`errors.${issue.code}`, { ...issue.meta })}
        </Text>
      ))}
    </View>
  );
};

export interface ApplicationFormHandle {
  readonly revealFirstError: () => void;
}

export const ApplicationForm = forwardRef<
  ApplicationFormHandle,
  {
    readonly form: ApplicationFormState;
    readonly currentStatus?: ApplicationStatus | undefined;
    readonly saving: boolean;
    readonly failure: string | null;
    readonly onSave: () => void;
    readonly onCancel: () => void;
    readonly header: ReactNode;
  }
>(function ApplicationForm(
  { form, currentStatus, saving, failure, onSave, onCancel, header },
  ref,
) {
  const { t, i18n } = useTranslation();
  const format = useMemo(() => createFormatter(i18n.language), [i18n.language]);
  const { values, set, touch, issuesFor } = form;

  const scroll = useRef<ScrollViewType>(null);
  const sectionY = useRef<Partial<Record<Section, number>>>({});
  const inputs = {
    company: useRef<TextInput>(null),
    position: useRef<TextInput>(null),
    jobUrl: useRef<TextInput>(null),
    location: useRef<TextInput>(null),
    salary: useRef<TextInput>(null),
    salaryMax: useRef<TextInput>(null),
    tags: useRef<TextInput>(null),
    notes: useRef<TextInput>(null),
  };
  const anchors = {
    source: useRef<ViewType>(null),
    workMode: useRef<ViewType>(null),
    status: useRef<ViewType>(null),
    appliedAt: useRef<ViewType>(null),
  };

  useImperativeHandle(ref, () => ({
    revealFirstError: () => {
      const first = form.issues[0];
      if (!first) return;
      const group = groupOf(first);
      scroll.current?.scrollTo({ y: Math.max(0, (sectionY.current[SECTION_OF[group]] ?? 0) - 16) });
      AccessibilityInfo.announceForAccessibility(t("mobile.reviewFields"));
      const input = group in inputs ? inputs[group as keyof typeof inputs].current : null;
      if (input) {
        input.focus();
        return;
      }
      const anchor = group in anchors ? anchors[group as keyof typeof anchors].current : null;
      const node = anchor ? findNodeHandle(anchor) : null;
      if (node) AccessibilityInfo.setAccessibilityFocus(node);
    },
  }));

  const layout = (section: Section) => (y: number) => {
    sectionY.current[section] = y;
  };

  const salaryPreview =
    values.salaryMin.trim() !== "" || values.salaryMax.trim() !== ""
      ? format.salary({
          ...(Number.isFinite(Number(values.salaryMin)) && values.salaryMin.trim() !== ""
            ? { min: Number(values.salaryMin) }
            : {}),
          ...(Number.isFinite(Number(values.salaryMax)) && values.salaryMax.trim() !== ""
            ? { max: Number(values.salaryMax) }
            : {}),
          currency: values.currency as (typeof CURRENCIES)[number],
        })
      : null;

  return (
    <SafeAreaView edges={["bottom", "left", "right"]} className="flex-1 bg-canvas">
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        className="flex-1"
      >
        <ScrollView
          ref={scroll}
          keyboardShouldPersistTaps="handled"
          contentContainerClassName="gap-6 p-4 pb-8"
        >
          {header}
          <Text className="text-sm text-ink-muted">{t("form.requiredHint")}</Text>

          <Group title={t("form.groups.offer")} onLayout={layout("offer")}>
            <TextField
              inputRef={inputs.company}
              label={t("form.fields.company")}
              required
              value={values.company}
              onChangeText={(text) => {
                set("company", text);
              }}
              onBlur={() => {
                touch("company");
              }}
              maxLength={LIMITS.company}
              autoCapitalize="words"
              returnKeyType="next"
              submitBehavior="submit"
              onSubmitEditing={() => inputs.position.current?.focus()}
              issues={issuesFor("company")}
            />
            <TextField
              inputRef={inputs.position}
              label={t("form.fields.position")}
              required
              value={values.position}
              onChangeText={(text) => {
                set("position", text);
              }}
              onBlur={() => {
                touch("position");
              }}
              maxLength={LIMITS.position}
              autoCapitalize="sentences"
              returnKeyType="next"
              submitBehavior="submit"
              onSubmitEditing={() => inputs.jobUrl.current?.focus()}
              issues={issuesFor("position")}
            />
            <TextField
              inputRef={inputs.jobUrl}
              label={t("form.fields.jobUrl")}
              value={values.jobUrl}
              onChangeText={(text) => {
                set("jobUrl", text);
              }}
              onBlur={() => {
                touch("jobUrl");
              }}
              keyboardType="url"
              placeholder={t("form.placeholders.jobUrl")}
              maxLength={LIMITS.jobUrl}
              returnKeyType="next"
              submitBehavior="submit"
              onSubmitEditing={() => inputs.location.current?.focus()}
              issues={issuesFor("jobUrl")}
            />
            <ChoiceGroup
              groupRef={anchors.source}
              label={t("form.fields.source")}
              required
              options={APPLICATION_SOURCES.map((source) => ({
                value: source,
                label: t(`source.${source}`),
              }))}
              selected={values.source}
              onSelect={(source) => {
                set("source", source);
                touch("source");
              }}
              issues={issuesFor("source")}
            />
            <ChoiceGroup
              groupRef={anchors.workMode}
              label={t("form.fields.workMode")}
              required
              options={WORK_MODES.map((mode) => ({ value: mode, label: t(`workMode.${mode}`) }))}
              selected={values.workMode}
              onSelect={(mode) => {
                set("workMode", mode);
                touch("workMode");
              }}
              issues={issuesFor("workMode")}
            />
            <TextField
              inputRef={inputs.location}
              label={t("form.fields.location")}
              value={values.location}
              onChangeText={(text) => {
                set("location", text);
              }}
              onBlur={() => {
                touch("location");
              }}
              placeholder={t("form.placeholders.location")}
              maxLength={LIMITS.location}
              autoCapitalize="words"
              issues={issuesFor("location")}
            />
          </Group>

          <Group title={t("form.groups.process")} onLayout={layout("process")}>
            {currentStatus === undefined ? (
              <ChoiceGroup
                groupRef={anchors.status}
                label={t("form.fields.status")}
                required
                options={INITIAL_STATUSES.map((status) => ({
                  value: status,
                  label: t(`status.${status}`),
                }))}
                selected={values.status}
                onSelect={(status) => {
                  form.setStatus(status);
                }}
                issues={issuesFor("status")}
              />
            ) : (
              <View className="gap-1">
                <Text className="text-sm font-medium text-ink">{t("form.currentStatus")}</Text>
                <Text className="text-base text-ink">{t(`status.${currentStatus}`)}</Text>
                <Text className="text-xs text-ink-muted">{t("form.statusHint")}</Text>
              </View>
            )}
            {showsAppliedAt(values.status) && (
              <DateField
                fieldRef={anchors.appliedAt}
                label={t("form.fields.appliedAt")}
                value={values.appliedAt}
                max={form.today()}
                issues={issuesFor("appliedAt")}
                onChange={(date) => {
                  set("appliedAt", date);
                  touch("appliedAt");
                }}
              />
            )}
          </Group>

          <Group title={t("form.groups.salary")} onLayout={layout("salary")}>
            <Text className="text-xs text-ink-muted">{t("form.hints.salary")}</Text>
            <View className="flex-row gap-3">
              <View className="flex-1">
                <TextField
                  inputRef={inputs.salary}
                  label={t("form.fields.salaryMin")}
                  value={values.salaryMin}
                  onChangeText={(text) => {
                    set("salaryMin", text);
                  }}
                  onBlur={() => {
                    touch("salary");
                  }}
                  keyboardType="number-pad"
                  returnKeyType="next"
                  submitBehavior="submit"
                  onSubmitEditing={() => inputs.salaryMax.current?.focus()}
                  issues={[]}
                />
              </View>
              <View className="flex-1">
                <TextField
                  inputRef={inputs.salaryMax}
                  label={t("form.fields.salaryMax")}
                  value={values.salaryMax}
                  onChangeText={(text) => {
                    set("salaryMax", text);
                  }}
                  onBlur={() => {
                    touch("salary");
                  }}
                  keyboardType="number-pad"
                  issues={[]}
                />
              </View>
            </View>
            <ChoiceGroup
              label={t("form.fields.currency")}
              options={CURRENCIES.map((currency) => ({ value: currency, label: currency }))}
              selected={values.currency}
              onSelect={(currency) => {
                set("currency", currency);
              }}
              issues={[]}
            />
            {salaryPreview && <Text className="text-sm text-ink">{salaryPreview}</Text>}
            {issuesFor("salary").map((issue) => (
              <Text key={`${issue.field}-${issue.code}`} className="text-sm text-danger">
                {t(`errors.${issue.code}`, { ...issue.meta })}
              </Text>
            ))}
          </Group>

          <Group title={t("form.groups.tags")} onLayout={layout("tags")}>
            <TagField
              inputRef={inputs.tags}
              label={t("form.groups.tags")}
              tags={values.tags}
              issues={issuesFor("tags")}
              onChange={(tags) => {
                set("tags", tags);
                touch("tags");
              }}
              onBlur={() => {
                touch("tags");
              }}
            />
          </Group>

          <Group title={t("form.groups.notes")} onLayout={layout("notes")}>
            <TextField
              inputRef={inputs.notes}
              label={t("form.fields.notes")}
              value={values.notes}
              onChangeText={(text) => {
                set("notes", text);
              }}
              onBlur={() => {
                touch("notes");
              }}
              multiline
              maxLength={LIMITS.notes}
              autoCapitalize="sentences"
              issues={issuesFor("notes")}
            />
            <Text className="self-end text-xs text-ink-muted">
              {t("form.hints.notesCount", { count: values.notes.length, max: LIMITS.notes })}
            </Text>
          </Group>
        </ScrollView>

        <View className="gap-2 border-t border-border bg-surface p-4">
          {failure && (
            <Text accessibilityRole="alert" className="text-sm text-danger">
              {failure}
            </Text>
          )}
          <View className="flex-row gap-3">
            <View className="flex-1">
              <Button variant="secondary" label={t("form.cancel")} onPress={onCancel} />
            </View>
            <View className="flex-1">
              <Button
                label={saving ? t("form.saving") : t("form.save")}
                busy={saving}
                onPress={onSave}
              />
            </View>
          </View>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
});
