// apps/web/src/ui/components/ApplicationCard.vue
<script setup lang="ts">
import type { ApplicationSummary } from "@applytrack/core";
import { STALE_AFTER_DAYS } from "@applytrack/core";
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { RouterLink } from "vue-router";

import { useFormat } from "../../composables/useFormat";
import AppIcon from "./AppIcon.vue";
import StatusBadge from "./StatusBadge.vue";

const MAX_TAGS = 3;

const props = defineProps<{ application: ApplicationSummary; showStatus?: boolean }>();

const { t } = useI18n();
const { daysAgo } = useFormat();

const visibleTags = computed(() => props.application.tags.slice(0, MAX_TAGS));
const hiddenTags = computed(() => props.application.tags.length - visibleTags.value.length);
const label = computed(() =>
  t("card.linkLabel", {
    company: props.application.company,
    position: props.application.position,
    status: t(`status.${props.application.status}`),
  }),
);
</script>

<template>
  <article
    class="group border-border bg-surface hover:border-accent relative rounded-lg border p-3 shadow-xs transition-colors"
  >
    <h3 class="text-ink truncate font-semibold" :title="application.company">
      <RouterLink
        :to="{ name: 'application', params: { id: application.id } }"
        :aria-label="label"
        class="after:absolute after:inset-0 after:rounded-lg focus-visible:outline-none"
      >
        {{ application.company }}
      </RouterLink>
    </h3>
    <p class="text-ink-muted mt-0.5 line-clamp-2 text-sm">{{ application.position }}</p>

    <div class="mt-3 flex flex-wrap items-center gap-1.5 text-xs">
      <StatusBadge v-if="showStatus" :status="application.status" />
      <span class="bg-surface-muted text-ink-muted rounded-full px-2 py-0.5">
        {{ t(`workMode.${application.workMode}`) }}
      </span>
      <span
        v-if="application.stale"
        class="bg-warning-soft text-warning inline-flex items-center gap-1 rounded-full px-2 py-0.5 font-medium"
        :title="t('card.staleHint', { days: STALE_AFTER_DAYS })"
      >
        <AppIcon name="clock" class="size-3.5" />
        {{ t("card.stale") }}
      </span>
    </div>

    <ul v-if="application.tags.length" class="mt-2 flex flex-wrap gap-1 text-xs">
      <li
        v-for="tag in visibleTags"
        :key="tag"
        class="border-border text-ink-muted rounded border px-1.5"
      >
        {{ tag }}
      </li>
      <li v-if="hiddenTags > 0" class="text-ink-muted px-1">
        {{ t("card.moreTags", { count: hiddenTags }) }}
      </li>
    </ul>

    <p class="text-ink-muted mt-3 text-xs">
      {{ t("card.updated", { when: daysAgo(application.daysSinceUpdate) }) }}
    </p>
  </article>
</template>

// apps/mobile/src/ui/ApplicationCard.tsx
import type { ApplicationSummary } from "@applytrack/core";
import { STALE_AFTER_DAYS } from "@applytrack/core";
import { COLORS } from "@applytrack/design-tokens";
import { createFormatter } from "@applytrack/presentation";
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Pressable, Text, View } from "react-native";

import { useIsDark } from "../theme/theme";
import { Icon } from "./Icon";

const MAX_TAGS = 3;

const Pill = ({
  label,
  tone = "muted",
}: {
  readonly label: string;
  readonly tone?: "muted" | "warning";
}) => (
  <View
    className={`rounded-full px-2 py-0.5 ${tone === "warning" ? "bg-warning-soft" : "bg-surface-muted"}`}
  >
    <Text className={`text-xs ${tone === "warning" ? "text-warning" : "text-ink-muted"}`}>
      {label}
    </Text>
  </View>
);

export const ApplicationCard = ({
  application,
  showStatus,
  onPress,
}: {
  readonly application: ApplicationSummary;
  readonly showStatus: boolean;
  readonly onPress: () => void;
}) => {
  const { t, i18n } = useTranslation();
  const dark = useIsDark();
  const format = useMemo(() => createFormatter(i18n.language), [i18n.language]);
  const status = t(`status.${application.status}`);
  const extraTags = application.tags.length - MAX_TAGS;

  const label = [
    t("card.linkLabel", {
      company: application.company,
      position: application.position,
      status,
    }),
    application.stale ? t("card.stale") : null,
    application.archived ? t("card.archived") : null,
  ]
    .filter(Boolean)
    .join(". ");

  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={label}
      onPress={onPress}
      className="gap-2 rounded-lg border border-border bg-surface p-4 active:opacity-80"
    >
      <Text numberOfLines={1} className="text-base font-semibold text-ink">
        {application.company}
      </Text>
      <Text numberOfLines={2} className="text-sm text-ink-muted">
        {application.position}
      </Text>
      <View className="flex-row flex-wrap items-center gap-2">
        {showStatus && <Pill label={status} />}
        <Pill label={t(`workMode.${application.workMode}`)} />
        {application.archived && <Pill label={t("card.archived")} />}
        {application.stale && (
          <View
            className="flex-row items-center gap-1 rounded-full bg-warning-soft px-2 py-0.5"
            accessibilityHint={t("card.staleHint", { days: STALE_AFTER_DAYS })}
          >
            <Icon name="clock" size={12} color={COLORS[dark ? "dark" : "light"].warning} />
            <Text className="text-xs font-medium text-warning">{t("card.stale")}</Text>
          </View>
        )}
      </View>
      {application.tags.length > 0 && (
        <View className="flex-row flex-wrap gap-1">
          {application.tags.slice(0, MAX_TAGS).map((tag) => (
            <Text key={tag} className="rounded bg-accent-soft px-2 py-0.5 text-xs text-ink">
              {tag}
            </Text>
          ))}
          {extraTags > 0 && (
            <Text className="px-1 py-0.5 text-xs text-ink-muted">
              {t("card.moreTags", { count: extraTags })}
            </Text>
          )}
        </View>
      )}
      <Text className="text-xs text-ink-muted">
        {t("card.updated", { when: format.daysAgo(application.daysSinceUpdate) })}
      </Text>
    </Pressable>
  );
};
