// apps/web/src/ui/form/TextField.vue
<script setup lang="ts">
import type { FieldIssue } from "@applytrack/core";
import { computed } from "vue";

import FieldErrors from "./FieldErrors.vue";

const props = withDefaults(
  defineProps<{
    name: string;
    label: string;
    issues: readonly FieldIssue[];
    type?: string;
    required?: boolean;
    maxlength?: number | undefined;
    placeholder?: string | undefined;
    hint?: string | undefined;
    max?: string | undefined;
    autocomplete?: string;
  }>(),
  {
    type: "text",
    autocomplete: "off",
    maxlength: undefined,
    placeholder: undefined,
    hint: undefined,
    max: undefined,
  },
);

const model = defineModel<string>({ required: true });
defineEmits<{ blur: [] }>();

const id = computed(() => `field-${props.name}`);
const describedBy = computed(
  () =>
    [props.hint ? `hint-${props.name}` : "", props.issues.length ? `error-${props.name}` : ""]
      .filter(Boolean)
      .join(" ") || undefined,
);
</script>

<template>
  <div class="flex flex-col gap-1">
    <label :for="id" class="text-sm font-medium">
      {{ label }}<span v-if="required" aria-hidden="true" class="text-danger"> *</span>
    </label>
    <input
      :id="id"
      :value="model"
      :type="type"
      :name="name"
      :maxlength="maxlength"
      :max="max"
      :placeholder="placeholder"
      :autocomplete="autocomplete"
      :aria-required="required || undefined"
      :aria-invalid="issues.length > 0 || undefined"
      :aria-describedby="describedBy"
      class="border-border bg-surface placeholder:text-ink-muted aria-invalid:border-danger min-h-11 rounded-md border px-3"
      @input="model = ($event.target as HTMLInputElement).value"
      @blur="$emit('blur')"
    />
    <p v-if="hint" :id="`hint-${name}`" class="text-ink-muted text-sm">{{ hint }}</p>
    <FieldErrors :id="`error-${name}`" :issues="issues" />
  </div>
</template>

// apps/mobile/src/ui/TextField.tsx
import type { FieldIssue } from "@applytrack/core";
import { COLORS } from "@applytrack/design-tokens";
import type { Ref } from "react";
import { useTranslation } from "react-i18next";
import type { TextInputProps } from "react-native";
import { Text, TextInput, View } from "react-native";

import { useIsDark } from "../theme/theme";

export const TextField = ({
  label,
  value,
  onChangeText,
  issues,
  inputRef,
  required = false,
  hint,
  ...input
}: {
  readonly label: string;
  readonly value: string;
  readonly onChangeText: (value: string) => void;
  readonly issues: readonly FieldIssue[];
  readonly inputRef?: Ref<TextInput>;
  readonly required?: boolean;
  readonly hint?: string | undefined;
} & Pick<
  TextInputProps,
  | "autoComplete"
  | "keyboardType"
  | "textContentType"
  | "onSubmitEditing"
  | "returnKeyType"
  | "maxLength"
  | "onBlur"
  | "placeholder"
  | "multiline"
  | "submitBehavior"
  | "autoCapitalize"
>) => {
  const { t } = useTranslation();
  const dark = useIsDark();
  const invalid = issues.length > 0;

  return (
    <View className="gap-1">
      <Text className="text-sm font-medium text-ink">
        {label}
        {required ? <Text className="text-danger"> *</Text> : null}
      </Text>
      <TextInput
        ref={inputRef}
        value={value}
        onChangeText={onChangeText}
        accessibilityLabel={label}
        autoCapitalize="none"
        autoCorrect={false}
        placeholderTextColor={COLORS[dark ? "dark" : "light"]["ink-muted"]}
        className={`min-h-12 rounded-md border bg-surface px-3 text-base text-ink ${
          input.multiline ? "min-h-28 py-2" : ""
        } ${invalid ? "border-danger" : "border-border"}`}
        {...input}
      />
      {hint ? <Text className="text-xs text-ink-muted">{hint}</Text> : null}
      {issues.map((issue) => (
        <Text
          key={`${issue.field}-${issue.code}`}
          accessibilityLiveRegion="polite"
          className="text-sm text-danger"
        >
          {t(`errors.${issue.code}`, { ...issue.meta })}
        </Text>
      ))}
    </View>
  );
};
